--liquibase formatted sql
--changeset uspr:GBP_12410_data runOnChange:true dbms:oracle,hsqldb stripComments:true failOnError:true

UPDATE MODULE
SET ENABLED='T'
where ID = 'BP_ECOMM_ADMIN_CONFIGURATIONS_TAXES';

UPDATE MODULE
SET ENABLED='T'
where ID = 'BP_ECOMM_ADMIN_CONFIGURATIONS_COUPONS';

UPDATE MODULE
SET ENABLED='T'
where ID = 'BP_ECOMM_OPERATION_CONFIGURATIONS';

UPDATE MODULE
SET ENABLED='T'
where ID = 'BP_ECOMM_BUSINESS_CONFIGURATIONS';

UPDATE MODULE
SET ENABLED='T'
where ID = 'BP_ECOMM_CUSTOM_CONFIGURATIONS_ACTIONS_VIEW_AND_EDIT_TAXES';

UPDATE MODULE
SET ENABLED='T'
where ID = 'BP_ECOMM_CUSTOM_CONFIGURATIONS_ACTIONS_VIEW_AND_EDIT_COUPONS';

UPDATE MODULE
SET ENABLED='T'
where ID = 'BP_EU_ADMIN_CONFIGURATIONS_TAXES';

UPDATE MODULE
SET ENABLED='T'
where ID = 'BP_EU_ADMIN_CONFIGURATIONS_COUPONS';

UPDATE MODULE
SET ENABLED='T'
where ID = 'BP_EU_OPERATION_CONFIGURATIONS';

UPDATE MODULE
SET ENABLED='T'
where ID = 'BP_EU_BUSINESS_CONFIGURATIONS';

UPDATE MODULE
SET ENABLED='T'
where ID = 'BP_EU_CUSTOM_TAXES';

UPDATE MODULE
SET ENABLED='T'
where ID = 'BP_EU_CUSTOM_COUPONS';


DELETE FROM MODULE_PERM WHERE PERMISSION='group-business-portal:merchant-information:get' AND MODULE_ID='BP_ECOMM_CUSTOM_CONFIGURATIONS_ACTIONS_VIEW';