--liquibase formatted sql
--changeset gbp:CSDM_2268_data runOnChange:true dbms:oracle stripComments:true failOnError:true

--SUBMODULES ADMIN
Insert into MODULE_ACCESS_LEVEL (SHOW,MODULE_ID,ENABLED)
values ('BUSINESS_RELATION_NAME','BP_ADMIN_INTEGRATE_STORE_ID_PASSWORD','T');
Insert into MODULE_ACCESS_LEVEL (SHOW,MODULE_ID,ENABLED)
values ('BUSINESS_RELATION_NAME','BP_ADMIN_INTEGRATE_API_KEYS','T');
Insert into MODULE_ACCESS_LEVEL (SHOW,MODULE_ID,ENABLED)
values ('BUSINESS_RELATION_NAME','BP_ADMIN_INTEGRATE_API_DOCUMENTATION','T');
Insert into MODULE_ACCESS_LEVEL (SHOW,MODULE_ID,ENABLED)
values ('BUSINESS_RELATION_NAME','BP_ADMIN_INTEGRATE_PAYMENT_METHODS','T');
Insert into MODULE_ACCESS_LEVEL (SHOW,MODULE_ID,ENABLED)
values ('BUSINESS_RELATION_NAME','BP_EU_ADMIN_INTEGRATE_APPLE_PAY','T');
Insert into MODULE_ACCESS_LEVEL (SHOW,MODULE_ID,ENABLED)
values ('BUSINESS_RELATION_NAME','BP_EU_ADMIN_MANAGE_SFTP_KEY','T');

Insert into MODULE_ACCESS_LEVEL (SHOW,MODULE_ID,ENABLED)
values ('BUSINESS_RELATION_NAME','BP_ADMIN_TRANSACTIONS_MERCHANT_LEVEL_AGGREGATIONS_FILTER_L1','T');
Insert into MODULE_ACCESS_LEVEL (SHOW,MODULE_ID,ENABLED)
values ('BUSINESS_RELATION_NAME','BP_ADMIN_TRANSACTIONS_DRILL_DOWN_MLE_LEVEL_L3','T');
Insert into MODULE_ACCESS_LEVEL (SHOW,MODULE_ID,ENABLED)
values ('BUSINESS_RELATION_NAME','BP_ADMIN_TRANSACTIONS_VIEW_TRANSACTION_RECORDS','T');
Insert into MODULE_ACCESS_LEVEL (SHOW,MODULE_ID,ENABLED)
values ('BUSINESS_RELATION_NAME','BP_ADMIN_TRANSACTIONS_DOWNLOAD_TRANSACTION_RECORDS','T');
Insert into MODULE_ACCESS_LEVEL (SHOW,MODULE_ID,ENABLED)
values ('BUSINESS_RELATION_NAME','BP_ADMIN_TRANSACTIONS_VIEW_DETAILED_TRANSACTION_HISTORY','T');
Insert into MODULE_ACCESS_LEVEL (SHOW,MODULE_ID,ENABLED)
values ('BUSINESS_RELATION_NAME','BP_ADMIN_TRANSACTIONS_CTA','T');
Insert into MODULE_ACCESS_LEVEL (SHOW,MODULE_ID,ENABLED)
values ('BUSINESS_RELATION_NAME','BP_ADMIN_TRANSACTIONS_CHARGEBACK_REPORTS_ACCOUNT','T');
Insert into MODULE_ACCESS_LEVEL (SHOW,MODULE_ID,ENABLED)
values ('BUSINESS_RELATION_NAME','BP_ADMIN_TRANSACTIONS_CHARGEBACK_REPORTS_MERCHANT','T');
Insert into MODULE_ACCESS_LEVEL (SHOW,MODULE_ID,ENABLED)
values ('BUSINESS_RELATION_NAME','BP_ADMIN_TRANSACTIONS_CHARGEBACK_REPORTS_DOWNLOAD','T');

Insert into MODULE_ACCESS_LEVEL (SHOW,MODULE_ID,ENABLED)
values ('BUSINESS_RELATION_NAME','BP_ADMIN_ACCOUNT_STATEMENT_VIEW_BALANCE_AND_STATEMENT','T');
Insert into MODULE_ACCESS_LEVEL (SHOW,MODULE_ID,ENABLED)
values ('BUSINESS_RELATION_NAME','BP_ADMIN_ACCOUNT_STATEMENT_DRILL_DOWN_TO_TRANSACTION','T');
Insert into MODULE_ACCESS_LEVEL (SHOW,MODULE_ID,ENABLED)
values ('BUSINESS_RELATION_NAME','BP_ADMIN_ACCOUNT_STATEMENT_IFR_VIEW_AND_DOWNLOAD','T');
Insert into MODULE_ACCESS_LEVEL (SHOW,MODULE_ID,ENABLED)
values ('BUSINESS_RELATION_NAME','BP_ADMIN_ACCOUNT_STATEMENT_DOWNLOAD_BALANCE_AND_STATEMENT','T');

Insert into MODULE_ACCESS_LEVEL (SHOW,MODULE_ID,ENABLED)
values ('BUSINESS_RELATION_NAME','BP_EU_ADMIN_VIRTUAL_TERMINAL_ACCEPT_PAYMENT','T');
Insert into MODULE_ACCESS_LEVEL (SHOW,MODULE_ID,ENABLED)
values ('BUSINESS_RELATION_NAME','BP_EU_ADMIN_VIRTUAL_TERMINAL_SETTINGS','T');

Insert into MODULE_ACCESS_LEVEL (SHOW,MODULE_ID,ENABLED)
values ('BUSINESS_RELATION_NAME','BP_EU_ADMIN_DIGITAL_INVOICING_GENERATE','T');
Insert into MODULE_ACCESS_LEVEL (SHOW,MODULE_ID,ENABLED)
values ('BUSINESS_RELATION_NAME','BP_EU_ADMIN_DIGITAL_INVOICING_SETTINGS','T');

Insert into MODULE_ACCESS_LEVEL (SHOW,MODULE_ID,ENABLED)
values ('BUSINESS_RELATION_NAME','BP_EU_ADMIN_CONFIGURATIONS_TAXES','T');
Insert into MODULE_ACCESS_LEVEL (SHOW,MODULE_ID,ENABLED)
values ('BUSINESS_RELATION_NAME','BP_EU_ADMIN_CONFIGURATIONS_BRANDING','T');
Insert into MODULE_ACCESS_LEVEL (SHOW,MODULE_ID,ENABLED)
values ('BUSINESS_RELATION_NAME','BP_EU_ADMIN_CONFIGURATIONS_WEBHOOKS','T');
Insert into MODULE_ACCESS_LEVEL (SHOW,MODULE_ID,ENABLED)
values ('BUSINESS_RELATION_NAME','BP_EU_ADMIN_CONFIGURATIONS_COUPONS','T');

Insert into MODULE_ACCESS_LEVEL (SHOW,MODULE_ID,ENABLED)
values ('BUSINESS_RELATION_NAME','BP_US_ADMIN_INTEGRATE_API_KEYS','T');
Insert into MODULE_ACCESS_LEVEL (SHOW,MODULE_ID,ENABLED)
values ('BUSINESS_RELATION_NAME','BP_US_ADMIN_INTEGRATE_PAYMENT_METHODS','T');
Insert into MODULE_ACCESS_LEVEL (SHOW,MODULE_ID,ENABLED)
values ('BUSINESS_RELATION_NAME','BP_US_ADMIN_INTEGRATE_API_DOCUMENTATION','T');
Insert into MODULE_ACCESS_LEVEL (SHOW,MODULE_ID,ENABLED)
values ('BUSINESS_RELATION_NAME','BP_US_ADMIN_INTEGRATE_APPLE_PAY','T');

--SUBMODULES DEVELOPER
Insert into MODULE_ACCESS_LEVEL (SHOW,MODULE_ID,ENABLED)
values ('BUSINESS_RELATION_NAME','BP_DEVELOPER_INTEGRATE_API_DOCUMENTATION','T');
Insert into MODULE_ACCESS_LEVEL (SHOW,MODULE_ID,ENABLED)
values ('BUSINESS_RELATION_NAME','BP_DEVELOPER_INTEGRATE_API_KEYS','T');
Insert into MODULE_ACCESS_LEVEL (SHOW,MODULE_ID,ENABLED)
values ('BUSINESS_RELATION_NAME','BP_DEVELOPER_INTEGRATE_STORE_ID_PASSWORD','T');

Insert into MODULE_ACCESS_LEVEL (SHOW,MODULE_ID,ENABLED)
values ('BUSINESS_RELATION_NAME','BP_DEVELOPER_TRANSACTIONS_MERCHANT_LEVEL_AGGREGATIONS_FILTER_L1','T');
Insert into MODULE_ACCESS_LEVEL (SHOW,MODULE_ID,ENABLED)
values ('BUSINESS_RELATION_NAME','BP_DEVELOPER_TRANSACTIONS_DRILL_DOWN_MLE_LEVEL_L3','T');
Insert into MODULE_ACCESS_LEVEL (SHOW,MODULE_ID,ENABLED)
values ('BUSINESS_RELATION_NAME','BP_DEVELOPER_TRANSACTIONS_VIEW_TRANSACTION_RECORDS','T');

Insert into MODULE_ACCESS_LEVEL (SHOW,MODULE_ID,ENABLED)
values ('BUSINESS_RELATION_NAME','BP_US_DEVELOPER_INTEGRATE_API_DOCUMENTATION','T');
Insert into MODULE_ACCESS_LEVEL (SHOW,MODULE_ID,ENABLED)
values ('BUSINESS_RELATION_NAME','BP_US_DEVELOPER_INTEGRATE_API_KEYS','T');

--SUBMODULES FINANCE
Insert into MODULE_ACCESS_LEVEL (SHOW,MODULE_ID,ENABLED)
values ('BUSINESS_RELATION_NAME','BP_BUSINESS_TRANSACTIONS_MERCHANT_LEVEL_AGGREGATIONS_FILTER_L1','T');
Insert into MODULE_ACCESS_LEVEL (SHOW,MODULE_ID,ENABLED)
values ('BUSINESS_RELATION_NAME','BP_BUSINESS_TRANSACTIONS_DRILL_DOWN_MLE_LEVEL_L3','T');
Insert into MODULE_ACCESS_LEVEL (SHOW,MODULE_ID,ENABLED)
values ('BUSINESS_RELATION_NAME','BP_BUSINESS_TRANSACTIONS_VIEW_TRANSACTION_RECORDS','T');
Insert into MODULE_ACCESS_LEVEL (SHOW,MODULE_ID,ENABLED)
values ('BUSINESS_RELATION_NAME','BP_BUSINESS_TRANSACTIONS_DOWNLOAD_TRANSACTION_RECORDS','T');
Insert into MODULE_ACCESS_LEVEL (SHOW,MODULE_ID,ENABLED)
values ('BUSINESS_RELATION_NAME','BP_BUSINESS_TRANSACTIONS_VIEW_DETAILED_TRANSACTION_HISTORY','T');
Insert into MODULE_ACCESS_LEVEL (SHOW,MODULE_ID,ENABLED)
values ('BUSINESS_RELATION_NAME','BP_BUSINESS_TRANSACTIONS_CHARGEBACK_REPORTS_ACCOUNT','T');
Insert into MODULE_ACCESS_LEVEL (SHOW,MODULE_ID,ENABLED)
values ('BUSINESS_RELATION_NAME','BP_BUSINESS_TRANSACTIONS_CHARGEBACK_REPORTS_MERCHANT','T');
Insert into MODULE_ACCESS_LEVEL (SHOW,MODULE_ID,ENABLED)
values ('BUSINESS_RELATION_NAME','BP_BUSINESS_TRANSACTIONS_CHARGEBACK_REPORTS_DOWNLOAD','T');

Insert into MODULE_ACCESS_LEVEL (SHOW,MODULE_ID,ENABLED)
values ('BUSINESS_RELATION_NAME','BP_ADMIN_ACCOUNT_STATEMENT_VIEW_BALANCE_AND_STATEMENT','T');
Insert into MODULE_ACCESS_LEVEL (SHOW,MODULE_ID,ENABLED)
values ('BUSINESS_RELATION_NAME','BP_ADMIN_ACCOUNT_STATEMENT_DRILL_DOWN_TO_TRANSACTION','T');
Insert into MODULE_ACCESS_LEVEL (SHOW,MODULE_ID,ENABLED)
values ('BUSINESS_RELATION_NAME','BP_ADMIN_ACCOUNT_STATEMENT_IFR_VIEW_AND_DOWNLOAD','T');
Insert into MODULE_ACCESS_LEVEL (SHOW,MODULE_ID,ENABLED)
values ('BUSINESS_RELATION_NAME','BP_ADMIN_ACCOUNT_STATEMENT_DOWNLOAD_BALANCE_AND_STATEMENT','T');

Insert into MODULE_ACCESS_LEVEL (SHOW,MODULE_ID,ENABLED)
values ('BUSINESS_RELATION_NAME','BP_EU_BUSINESS_VIRTUAL_TERMINAL_ACCEPT_PAYMENT','T');

Insert into MODULE_ACCESS_LEVEL (SHOW,MODULE_ID,ENABLED)
values ('BUSINESS_RELATION_NAME','BP_EU_BUSINESS_DIGITAL_INVOICING_GENERATE','T');

Insert into MODULE_ACCESS_LEVEL (SHOW,MODULE_ID,ENABLED)
values ('BUSINESS_RELATION_NAME','BP_EU_BUSINESS_CONFIGURATIONS_TAXES','T');
Insert into MODULE_ACCESS_LEVEL (SHOW,MODULE_ID,ENABLED)
values ('BUSINESS_RELATION_NAME','BP_EU_BUSINESS_CONFIGURATIONS_COUPONS','T');

--SUBMODULES OPERATION
Insert into MODULE_ACCESS_LEVEL (SHOW,MODULE_ID,ENABLED)
values ('BUSINESS_RELATION_NAME','BP_EU_OPERATION_CONFIGURATIONS_TAXES','T');
Insert into MODULE_ACCESS_LEVEL (SHOW,MODULE_ID,ENABLED)
values ('BUSINESS_RELATION_NAME','BP_EU_OPERATION_CONFIGURATIONS_COUPONS','T');

Insert into MODULE_ACCESS_LEVEL (SHOW,MODULE_ID,ENABLED)
values ('BUSINESS_RELATION_NAME','BP_EU_OPERATION_DIGITAL_INVOICING_GENERATE','T');

--SUBMODULES CUSTOM
Insert into MODULE_ACCESS_LEVEL (SHOW,MODULE_ID,ENABLED)
values ('BUSINESS_RELATION_NAME','BP_CUSTOM_TRANSACTIONS_PERMS','T');
Insert into MODULE_ACCESS_LEVEL (SHOW,MODULE_ID,ENABLED)
values ('BUSINESS_RELATION_NAME','BP_CUSTOM_TRANSACTIONS_ACTIONS','T');

Insert into MODULE_ACCESS_LEVEL (SHOW,MODULE_ID,ENABLED)
values ('BUSINESS_RELATION_NAME','BP_CUSTOM_PAYMENT_METHODS_ACTIONS','T');

Insert into MODULE_ACCESS_LEVEL (SHOW,MODULE_ID,ENABLED)
values ('BUSINESS_RELATION_NAME','BP_CUSTOM_API_KEYS_ACTIONS','T');

Insert into MODULE_ACCESS_LEVEL (SHOW,MODULE_ID,ENABLED)
values ('BUSINESS_RELATION_NAME','BP_CUSTOM_STORE_ID_PASSWORD_ACTIONS','T');

Insert into MODULE_ACCESS_LEVEL (SHOW,MODULE_ID,ENABLED)
values ('BUSINESS_RELATION_NAME','BP_CUSTOM_INVOICES_ACTIONS','T');

Insert into MODULE_ACCESS_LEVEL (SHOW,MODULE_ID,ENABLED)
values ('BUSINESS_RELATION_NAME','BP_CUSTOM_ACCOUNT_STATEMENT_ACTIONS','T');

Insert into MODULE_ACCESS_LEVEL (SHOW,MODULE_ID,ENABLED)
values ('BUSINESS_RELATION_NAME','BP_CUSTOM_IFR_ACTIONS','T');

Insert into MODULE_ACCESS_LEVEL (SHOW,MODULE_ID,ENABLED)
values ('BUSINESS_RELATION_NAME','BP_EU_CUSTOM_VIRTUAL_TERMINAL_ACTIONS','T');

Insert into MODULE_ACCESS_LEVEL (SHOW,MODULE_ID,ENABLED)
values ('BUSINESS_RELATION_NAME','BP_EU_CUSTOM_DIGITAL_INVOICING_ACTIONS','T');

Insert into MODULE_ACCESS_LEVEL (SHOW,MODULE_ID,ENABLED)
values ('BUSINESS_RELATION_NAME','BP_CUSTOM_BRANDING_PERMISSIONS','T');

Insert into MODULE_ACCESS_LEVEL (SHOW,MODULE_ID,ENABLED)
values ('BUSINESS_RELATION_NAME','BP_EU_CUSTOM_TAXES_ACTIONS','T');

Insert into MODULE_ACCESS_LEVEL (SHOW,MODULE_ID,ENABLED)
values ('BUSINESS_RELATION_NAME','BP_EU_CUSTOM_COUPONS_ACTIONS','T');

Insert into MODULE_ACCESS_LEVEL (SHOW,MODULE_ID,ENABLED)
values ('BUSINESS_RELATION_NAME','BP_CUSTOM_WEBHOOKS_PERMISSIONS','T');

Insert into MODULE_ACCESS_LEVEL (SHOW,MODULE_ID,ENABLED)
values ('BUSINESS_RELATION_NAME','BP_EU_CUSTOM_MERCHANT_INFORMATION_ACTIONS','T');
