--liquibase formatted sql
--changeset gbp:GBP_11039_data runOnChange:true dbms:oracle,hsqldb stripComments:true failOnError:true

--MODULE_ACCESS_LEVEL
Insert into MODULE_ACCESS_LEVEL (SHOW,MODULE_ID,ENABLED)
values ('PMLE','BP_ECOMM_OPERATION_CONFIGURATIONS','T');
Insert into MODULE_ACCESS_LEVEL (SHOW,MODULE_ID,ENABLED)
values ('MLE','BP_ECOMM_OPERATION_CONFIGURATIONS','T');
Insert into MODULE_ACCESS_LEVEL (SHOW,MODULE_ID,ENABLED)
values ('PMLE','BP_ECOMM_OPERATION_CONFIGURATIONS_TAXES_AND_COUPONS','T');
Insert into MODULE_ACCESS_LEVEL (SHOW,MODULE_ID,ENABLED)
values ('MLE','BP_ECOMM_OPERATION_CONFIGURATIONS_TAXES_AND_COUPONS','T');
Insert into MODULE_ACCESS_LEVEL (SHOW,MODULE_ID,ENABLED)
values ('PMLE','BP_ECOMM_BUSINESS_CONFIGURATIONS','T');
Insert into MODULE_ACCESS_LEVEL (SHOW,MODULE_ID,ENABLED)
values ('MLE','BP_ECOMM_BUSINESS_CONFIGURATIONS','T');
Insert into MODULE_ACCESS_LEVEL (SHOW,MODULE_ID,ENABLED)
values ('PMLE','BP_ECOMM_BUSINESS_CONFIGURATIONS_TAXES_AND_COUPONS','T');
Insert into MODULE_ACCESS_LEVEL (SHOW,MODULE_ID,ENABLED)
values ('MLE','BP_ECOMM_BUSINESS_CONFIGURATIONS_TAXES_AND_COUPONS','T');

--MODULE_ACCESS_LEVEL
Update MODULE set EDITABLE = 'T' where ID = 'BP_ECOMM_CUSTOM_CONFIGURATIONS_ACTIONS_VIEW_AND_EDIT_BRANDING';
Update MODULE set EDITABLE = 'T' where ID = 'BP_ECOMM_CUSTOM_CONFIGURATIONS_ACTIONS_VIEW_AND_EDIT_TAXES';
Update MODULE set EDITABLE = 'T' where ID = 'BP_ECOMM_CUSTOM_CONFIGURATIONS_ACTIONS_VIEW_AND_EDIT_COUPONS';