--liquibase formatted sql
--changeset gbp:POR_958_data runOnChange:true dbms:oracle stripComments:true failOnError:true

--MODULE_ACCESS_LEVEL
DELETE FROM MODULE_ACCESS_LEVEL WHERE SHOW = 'MLE' AND MODULE_ID = 'BP_US_ADMIN_INTEGRATE';
DELETE FROM MODULE_ACCESS_LEVEL WHERE SHOW = 'MLE' AND MODULE_ID = 'BP_US_ADMIN_INTEGRATE_PAYMENT_METHODS';
DELETE FROM MODULE_ACCESS_LEVEL WHERE SHOW = 'MLE' AND MODULE_ID = 'BP_US_DEVELOPER_INTEGRATE';

