--liquibase formatted sql
--changeset gbp:GBP_11498_data runOnChange:true dbms:oracle stripComments:true failOnError:true

-- TO REMOVE DUPLICATE MODULE ACCESS LEVEL VOILATING KEY CONTRAINTS.
DELETE FROM MODULE_ACCESS_LEVEL
WHERE rowid not in
      (SELECT MIN(rowid)
       FROM MODULE_ACCESS_LEVEL
       GROUP BY MODULE_ID, SHOW);

UPDATE MODULE  SET PARENT_ID = 'BP_EU_ADMIN_CONFIGURATIONS' WHERE ID='BP_EU_ADMIN_CONFIGURATIONS_TAXES';
UPDATE MODULE  SET PARENT_ID = 'BP_EU_ADMIN_CONFIGURATIONS' WHERE ID='BP_EU_ADMIN_CONFIGURATIONS_COUPONS';

DELETE FROM MODULE_PERM WHERE MODULE_ID='BP_CUSTOM_BRANDING_PERMISSIONS_VIEW';
DELETE FROM MODULE_ACCESS_LEVEL WHERE MODULE_ID='BP_CUSTOM_BRANDING_PERMISSIONS_VIEW';
DELETE FROM MODULE WHERE ID = 'BP_CUSTOM_BRANDING_PERMISSIONS_VIEW';

UPDATE MODULE SET LABEL = 'Tax Configuration' WHERE ID='BP_EU_CUSTOM_TAXES';
